### PR TITLE
Use custom fork of loyd/readability.rs

### PR DESCRIPTION
**Pull request by mre**
Use the readability library from
https://github.com/readable-app/readability.rs/pull/1

This produces better results in our
manual tests.

### CODE REVIEW

**Comment by mre** [comment]
@jfmontanaro that's based on your work and it works great locally. To deploy it we need to publish our fork of `loyd/readability.rs` on crates.io.

**Comment by jfmontanaro** [comment]
@mre Sounds good, I published to crates.io as [readable-readability](https://crates.io/crates/readable-readability/0.2.0) because all the shorter variants were taken. Just publishing manually for now, but eventually I will get CI set up to build/test/publish etc.

**Comment by mre** [comment]
Cool cool. Thanks a lot. If you want you can adjust the PR for the app now and merge it. I'll do the deployment then or we can integrate the shuttle GitHub action.

**Comment by jfmontanaro** [comment]
Ok, updated and everything seems to work locally, so I merged it in.

**Comment by mre** [comment]
Very nice. Thank you. I deployed the new version. ✨

**Pull request merged**
